### ISSUE TITLE
Less secure 

### ISSUE THREAD

**Issue by HkopMD** [sh-dv/hat.sh#26]
isn't xchacha20poly1305 less secure than AES

**Comment by HkopMD** [comment]
Sorry for a not issue

**Comment by sh-dv** [comment]
> 
> 
> isn't xchacha20poly1305 less secure than AES

No. [XChaCha with Poly1305](https://doc.libsodium.org/secret-key_cryptography/aead/chacha20-poly1305/xchacha20-poly1305_construction) has a larger security margin than [AES-GCM](https://doc.libsodium.org/secret-key_cryptography/aead/aes-256-gcm).
