### ISSUE TITLE
Support for asymmetric public-private key encrpytion

### ISSUE THREAD

**Issue by Toflar** [sh-dv/hat.sh#29]
Hey there!

I found this awesome project while looking for cross platform apps that support libsodium file encryption/decryption.
It's so great to see things like this coming to the browser so people do not have to worry about installing any tools and using the command line etc. Great job!

Because I could not find any reference to public-private key support: Do you plan on adding something like that?
Of course not asking you to do it for free but just generally asking for a statement whether you would be willing to have support for it in hat.sh :)
That would enable us to get rid of sending the secret alltogether.
I imagine the process something like this:

1. Allow to generate a new key pair and download the files. Maybe the public key can be shown in ASCII format to copy right away.
2. I can then send the public key to the person I want to receive the file from
3. That person can encrypt the file using the public key (so we need another option besides entering a symmetric password)
4. The receiving person can select the private key file (so another option here too) while decrypting
5. Done :-)

Or did you not add support for it for any specific reason?
Thanks and keep up the great work!

**Comment by sh-dv** [comment]
> Great job!

Thanks! glad you like it.

Thank you for your suggestion. It is definitely something we thought about many times. This is not yet implemented due to multiple reasons. Mainly because it takes away from the vision of this web app, which is a simple single file encryption with a password. I hope in the future this will be implemented eventually, what do you think?


> Or did you not add support for it for any specific reason?

Yes, sender authentication, which plays a crucial part in this scenario.

> I can then send the public key to the person I want to receive the file from

The recipient must be sure that the file was encrypted and sent to them from the person (who shared keys with) they intended them to be. for example if i receive a file encrypted with my public key that i have shared with someone, i can't be sure that they are the one who encrypted the file and sent it to me, it could be anyone (middle man) who used my public key to encrypt the file.
This could be solved by implementing hybrid encryption where the sender encrypts the file with their own private key and the receiver public key. And then the recipient decrypts the file with their own private key and the sender public key. that way you can be sure that the encrypted file came from the sender you shared public keys with.

**Comment by Toflar** [comment]
I see! To me, that's yet another level on top of the basic sealing. Right now, if I'm using hat.sh to encrypt and send the data elsewhere, there's no way to know that it came from me either. But on top of that, I also have to send the secret.
With basic sealing functionality at least that problem would be solved.

The reason why I'm asking is basically that I could not find any good GUI for libsodium. As developers, we have a variety of options to choose from to work on CLI but regular users are mostly lost.
And with hat.sh they would not even have to install any additional software!
I could get the public key from a customer once and whenever I send them stuff, I can sign it with their public key and they can decrypt it. No need to share any passwords anymore.

Yes, that does not solve the problem of authenticated encryption but again, to me that's just yet another level on top :)

**Comment by sh-dv** [comment]
I understand, this should be implemented in hat.sh in the future for sure. For now, if you are looking for a GUI that may satisfy your needs (not libsodium), you should be looking for something like [openpgp](https://www.openpgp.org/software/)

**Comment by sh-dv** [comment]
Asymmetric public key cryptography is coming in the next version. If you like to test it out go [here](https://dev.hat.sh/). Would love to hear your feedback as soon as you try it.

**Comment by Toflar** [comment]
Oh wow!!! This is awesome, it works like a charm and looks absolutely gorgeous!

What would be great is if one could link to the decrypt page with the public key prepouplated already. Something like `dev.sh?tab=decrypt&public_key=...`. Would make it easer for the user as they do not have to copy the sender public key manually then :)

So you decided to only support authenticated asymmetric encryption and decription. No plans to support anonymous ones too then?

**Comment by sh-dv** [comment]
Thank!



> What would be great is if one could link to the decrypt page with the public key prepouplated already. Something like `dev.sh?tab=decrypt&public_key=...`. Would make it easer for the user as they do not have to copy the sender public key manually then :)

Sure, it is something currently in development too.


> So you decided to only support authenticated asymmetric encryption and decryption. No plans to support anonymous ones too then?

No plans for now, and i don't think it's gonna happen too. It takes away from the vision of the app.

**Comment by sh-dv** [comment]
> Sure, it is something currently in development too.
> 
> > So you decided to only support authenticated asymmetric encryption and decryption. No plans to support anonymous ones too then?

this is live now in [dev](https://dev.hat.sh/). let me know how the user experience is like.

**Comment by Toflar** [comment]
Works nicely when encrypting decrypting with hat.sh! Great job!

However, I cannot seem to get it working when the encryption happened with libsodium in another programming language which is [supposed to be one of the key advantages of libsodium](https://doc.libsodium.org/quickstart#is-libsodium-cross-platform).

Maybe it's because of the different formats of the respective keys which is currently undocumented so it's hard to find out, what's expected by hat.sh :)

**Comment by sh-dv** [comment]
thanks. Maybe it's not using the same algorithms + Hat.sh adds a unique encryption signature to the encrypted file.
