### ISSUE TITLE
Decryption fails on chromium when running with flag "--js-flags=--jitless".

### ISSUE THREAD

**Issue by tankaras** [sh-dv/hat.sh#38]
Env: Start chromium with flag "--js-flags=--jitless". Decrypt file with password.

Issue: Action spins endlessly. No download happens.

**Comment by sh-dv** [comment]
> Action spins endlessly. No download happens.


Hey, Just made a test, that's something too look into, thanks for raising the issue.

V8 engine JIT-less doesn't support WebAssembly. See [here](https://v8.dev/blog/jitless). 
The app uses [libsodium.js](https://github.com/jedisct1/libsodium.js/), which is the [libsodium](https://github.com/jedisct1/libsodium) crypto library compiled to WebAssembly and pure JavaScript.

Chromium jitless doesn't support WebAssembly yet, so hat.sh is not expected to run with jitless yet.
This issue will be reopened and proper testing will be done once V8 jitless supports WebAssembly
