### ISSUE TITLE
No longer works in Brave and some Chrome browsers?

### ISSUE THREAD

**Issue by berndwa** [sh-dv/hat.sh#43]
I noticed that I can't use the app in the Brave browser. The button "Browse file" has no function. and when I use drag and drop for the file, at the end of the encryption the encrypted file does not download.

**Comment by sh-dv** [comment]
Hat.sh works great on Brave browser.
What operation system do you have? Or are you on the mobile ?

**Comment by berndwa** [comment]
Sry I think it was only a one time failure of Brave. After a restart everything works fine again! 

So sorry for opening this issue! I still love your work! :-)

**Comment by sh-dv** [comment]
No worries. Thanks.
