### ISSUE TITLE
How To Update The Self-Hosted hat.sh Website?

### ISSUE THREAD

**Issue by Nihal247** [sh-dv/hat.sh#54]
I've self hosted the website locally, but how can I regularly update it with the changes made in hat.sh here? I wonder if there's any command to update.

Thank you in advance.

**Comment by sh-dv** [comment]
Hey
If you have used git to clone the repo, you can simply use the command `git pull`.
Or you can clone the repo again and run `npm install` if you have cloned it manually.
If you are using it as a docker container then you should update to the latest image tag.

**Comment by Nihal247** [comment]
@sh-dv thanks for your help!
