### ISSUE TITLE
Add DNSSEC record

### ISSUE THREAD

**Issue by t3dium** [sh-dv/hat.sh#59]
My dns logs and a whois search indicates none of the instances of hat.sh support dnssec.

Since hat.sh uses namecheap it should be fairly easy to implement as they have a [setting ](https://www.namecheap.com/support/knowledgebase/article.aspx/9722/2232/managing-dnssec-for-domains-pointed-to-custom-dns/) for it, and can be pretty important on a website like this where confidential files are likely to be uploaded.

**Comment by sh-dv** [comment]
This should be looked into! Thanks.
