### ISSUE TITLE
Issues with self-hosted deployment.

### ISSUE THREAD

**Issue by curtisrecords** [sh-dv/hat.sh#70]
Hello, my name is CurtisAsia.

- Reason: When I was building a self-hosted version (website), I wanted to put hat.sh in a folder like this: https://example.com/hat.sh/ 

- Try: Following the Github documentation and compiling with nvm, I see that there are many 404 requests in the Console, and many of them occur in the _next directory and the ico/png resource file; later, I found some things on the Internet, and it appears that next.js will have this type of question (Maybe I won't fix it.. sorry) Later, I tried the Docker self-hosted version, but I still had same issue after using Nginx Proxy.

- Result: How should I deploy it so that it can be accessed in the website's subdirectory? like https://example.com/hat.sh/

**Comment by curtisrecords** [comment]
nvm compilation and docker deployment are normal and error-free; perhaps my requirements are unusual...

**Comment by sh-dv** [comment]
Hello, i tried reproducing the same thing you did but had no errors, maybe try to build the app (npm run build) and move that build folder to the directory.

**Comment by curtisrecords** [comment]
Okay, thank you; I'll try again later.
